[package]
name = "oracle-function"
version = "0.1.0"
edition = "2021"

[dependencies]
# We use 0.29 with 'macros' to ensure environment detection works
switchboard-solana = { version = "0.29", features = ["macros"] }
solana-sdk = "1.18"
tokio = { version = "1", features = ["full"] }
sha2 = "0.10"